# MAIN

baseURL = '/'
languageCode = 'ru'
title = 'AnLar'

defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = true

#theme = 'ananke'
#theme = 'flat'
theme = 'mainroad'
#theme = 'simple-style'


# SECURITY

# required to access asciidoctor
[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]


# MENU

[languages]

  [languages.ru]
    title = 'Блог AnLar'
    weight = -1
[[languages.ru.menu.main]]
      name = 'Блог'
      url = '/ru'
      weight = -10
[[languages.ru.menu.main]]
      name = 'Архив'
      url = '/ru/post'
      weight = -9
[[languages.ru.menu.main]]
      name = 'Категории'
      url = '/ru/categories'
      weight = -8
[[languages.ru.menu.main]]
      name = 'Теги'
      url = '/ru/tags'
      weight = -7
[[languages.ru.menu.main]]
      name = 'Обо мне'
      url = '/ru/about'
      weight = -6

  [languages.en]
    title = 'Blog AnLar'
    weight = 0
[[languages.en.menu.main]]
      name = 'Blog'
      url = '/en'
      weight = -10
[[languages.en.menu.main]]
      name = 'Archive'
      url = '/en/post'
      weight = -9
[[languages.en.menu.main]]
      name = 'Categories'
      url = '/en/categories'
      weight = -8
[[languages.en.menu.main]]
      name = 'Tags'
      url = '/en/tags'
      weight = -7
[[languages.en.menu.main]]
      name = 'About'
      url = '/en/about'
      weight = -6


# THEME: MAINROAD

[Params]
  post_meta = ["date", "categories"]
  dateformat = "2006-01-02"
  customCSS = ["css/coderay.css"]

[Params.sidebar]
  home = "right"
  list = "right"
  single = false
  widgets = ["recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5
  categories_counter = true
  tags_counter = true

[Params.widgets.social]
  github = "anlar"
  linkedin = "anton-larionov"


# ASCIIDOCTOR

[markup.asciidocExt]
  extensions = ["asciidoctor-diagram"]
  workingFolderCurrent = true
  [markup.asciidocExt.attributes]
    source-highlighter = "coderay"

