baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'ananke'

#menu = 'main'
#sectionPagesMenu = "main"

[menu]
[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = -110
[[menu.main]]
  name = 'Blog'
  url = '/post/'
  weight = -100

#defaultContentLanguage = 'en'
[languages]
  [languages.en]
    title = 'Blog in EN'
    weight = 1
  [languages.ru]
    title = 'Блог РУ'
    weight = 2

# required to access asciidoctor
[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]

